# Generated by Django 2.2.9 on 2020-01-21 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('pages', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Reading date')),
                ('chapter', models.CharField(choices=[('1', '< 1 Chapter'), ('2', '1-2 Chapters'), ('3', '3+ Chapters')], default='1', max_length=1)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Reading')),
            ],
        ),
    ]
