# Generated by Django 2.2.9 on 2020-01-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Reading date')),
                ('chapter', models.CharField(choices=[('1', '<1 Chapter'), ('2', '1/2 Chapters'), ('3', '3+ Chapters')], default='1', max_length=1)),
            ],
        ),
    ]
