# Generated by Django 2.2.9 on 2020-01-22 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='notes',
            field=models.ManyToManyField(to='main_app.Note'),
        ),
    ]
