# Generated by Django 2.2.9 on 2020-01-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_reading_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='color',
            field=models.CharField(default='..', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='bookmark',
            field=models.CharField(max_length=50),
        ),
    ]
